INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Clara Maria', 'clara@gmail.com', '1990-03-17');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Antonio José', 'antoniojs@gmail.com', '1983-05-01');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Rita de Cassia', 'ritacassia@gmail.com', '1994-12-05');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Carlos Alberto', 'albertocarlos@gmail.com', '2000-08-25');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Ana Maria', 'ana@gmail.com', '1990-03-17');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'José Miguel', 'migueljs@gmail.com', '1950-05-01');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Cassia Augusta', 'augustac@gmail.com', '1994-12-05');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Alberto Carlos', 'carlosalberto@gmail.com', '2000-08-25');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Jessica Abreu', 'jessica@gmail.com', '2004-03-18');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Julia Maria', 'mariaj@gmail.com', '1973-07-01');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Rita Gonçalves', 'goncalves@gmail.com', '1995-09-18');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Roberto Carlos', 'carlosrb@gmail.com', '1999-12-15');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Benicio Silva', 'silvab@gmail.com', '1995-12-05');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Alberto Torres', 'albertoctorres@gmail.com', '2000-08-25');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Maria do Socorro', 'socorromaria@gmail.com', '1990-03-17');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Miguel Augusto', 'miguelag@gmail.com', '1983-05-01');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Bernado do Nascimento', 'bnascimento@gmail.com', '1990-03-17');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Suelen Gomes', 'suelengm@gmail.com', '1994-12-05');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Mario Jose', 'jsmario@gmail.com', '2000-08-25');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Bruna Carla', 'brunacarla.com', '1990-03-17');
INSERT INTO tb_person(name, email, birth_date) VALUES ( 'Diego Miguel', 'migueldiego@gmail.com', '1983-05-01');